version: "3.5"
services:
  # worker
  worker:
    image: jasonsoft/starter:latest
    depends_on:
      - event
      - wallet
    volumes:
      - "${LOCAL_WORKSPACE_FOLDER}/config/app.yml:/app/config/app.yml"
    command: /app/starter worker

  # wallet
  wallet:
    image: jasonsoft/starter:latest
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/config/app.yml:/app/config/app.yml
    command: /app/starter wallet

  # event
  event:
    image: jasonsoft/starter:latest
    volumes:
      - "${LOCAL_WORKSPACE_FOLDER}/config/app.yml:/app/config/app.yml"
    command: /app/starter event

  # frontend
  frontend:
    image: jasonsoft/starter:latest
    depends_on:
      - event
      - wallet
    ports:
      - "10081:10081"
    volumes:
      - "${LOCAL_WORKSPACE_FOLDER}/config/app.yml:/app/config/app.yml"
    command: /app/starter frontend
  # event-dapr:
  #   image: "daprio/daprd:0.10.0"
  #   command: [
  #     "./daprd",
  #     "-app-id", "event",
  #     "-app-port", "10010",
  #     "-placement-host-address", "placement:50006" # Dapr's placement service can be reach via the docker DNS entry
  #     ]
  #   volumes:
  #       - "./components/:/components" # Mount our components folder for the runtime to use
  #   depends_on:
  #     - event
  #   network_mode: "service:event" # Attach the event-dapr service to the event network namespace
