// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/event/proto/event.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublishedStatus int32

const (
	PublishedStatus_Draft     PublishedStatus = 0
	PublishedStatus_Published PublishedStatus = 1
)

var PublishedStatus_name = map[int32]string{
	0: "Draft",
	1: "Published",
}
var PublishedStatus_value = map[string]int32{
	"Draft":     0,
	"Published": 1,
}

func (x PublishedStatus) String() string {
	return proto.EnumName(PublishedStatus_name, int32(x))
}
func (PublishedStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_event_752b23ec75c21b93, []int{0}
}

type Event struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PublishedStatus      PublishedStatus      `protobuf:"varint,4,opt,name=published_status,json=publishedStatus,proto3,enum=proto.PublishedStatus" json:"published_status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_752b23ec75c21b93, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetPublishedStatus() PublishedStatus {
	if m != nil {
		return m.PublishedStatus
	}
	return PublishedStatus_Draft
}

func (m *Event) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type GetEventsResponse struct {
	Data                 []*Event `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_752b23ec75c21b93, []int{1}
}
func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (dst *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(dst, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetData() []*Event {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdatePublishStatusRequest struct {
	EventId              int64           `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TransId              string          `protobuf:"bytes,2,opt,name=trans_id,json=transId,proto3" json:"trans_id,omitempty"`
	PublishedStatus      PublishedStatus `protobuf:"varint,3,opt,name=published_status,json=publishedStatus,proto3,enum=proto.PublishedStatus" json:"published_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdatePublishStatusRequest) Reset()         { *m = UpdatePublishStatusRequest{} }
func (m *UpdatePublishStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePublishStatusRequest) ProtoMessage()    {}
func (*UpdatePublishStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_752b23ec75c21b93, []int{2}
}
func (m *UpdatePublishStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePublishStatusRequest.Unmarshal(m, b)
}
func (m *UpdatePublishStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePublishStatusRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePublishStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePublishStatusRequest.Merge(dst, src)
}
func (m *UpdatePublishStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePublishStatusRequest.Size(m)
}
func (m *UpdatePublishStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePublishStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePublishStatusRequest proto.InternalMessageInfo

func (m *UpdatePublishStatusRequest) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *UpdatePublishStatusRequest) GetTransId() string {
	if m != nil {
		return m.TransId
	}
	return ""
}

func (m *UpdatePublishStatusRequest) GetPublishedStatus() PublishedStatus {
	if m != nil {
		return m.PublishedStatus
	}
	return PublishedStatus_Draft
}

func init() {
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*GetEventsResponse)(nil), "proto.GetEventsResponse")
	proto.RegisterType((*UpdatePublishStatusRequest)(nil), "proto.UpdatePublishStatusRequest")
	proto.RegisterEnum("proto.PublishedStatus", PublishedStatus_name, PublishedStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	GetEvents(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetEventsResponse, error)
	UpdatePublishStatus(ctx context.Context, in *UpdatePublishStatusRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) GetEvents(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, "/proto.EventService/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdatePublishStatus(ctx context.Context, in *UpdatePublishStatusRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.EventService/UpdatePublishStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	GetEvents(context.Context, *empty.Empty) (*GetEventsResponse, error)
	UpdatePublishStatus(context.Context, *UpdatePublishStatusRequest) (*empty.Empty, error)
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvents(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdatePublishStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePublishStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdatePublishStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EventService/UpdatePublishStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdatePublishStatus(ctx, req.(*UpdatePublishStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _EventService_GetEvents_Handler,
		},
		{
			MethodName: "UpdatePublishStatus",
			Handler:    _EventService_UpdatePublishStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/event/proto/event.proto",
}

func init() { proto.RegisterFile("pkg/event/proto/event.proto", fileDescriptor_event_752b23ec75c21b93) }

var fileDescriptor_event_752b23ec75c21b93 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x71, 0xb3, 0x61, 0xc9, 0x74, 0xd9, 0x2d, 0x06, 0xad, 0x42, 0x7a, 0x20, 0xf4, 0x14,
	0x81, 0x94, 0x4a, 0x41, 0x1c, 0x38, 0x70, 0xa8, 0x44, 0x85, 0x7a, 0xab, 0x52, 0x38, 0x57, 0x6e,
	0x3d, 0x2d, 0x16, 0x6d, 0x62, 0xe2, 0x49, 0x25, 0x3e, 0x08, 0x67, 0x3e, 0x11, 0xdf, 0x09, 0xc5,
	0x4e, 0x2b, 0xe8, 0x9f, 0xc3, 0x9e, 0xe2, 0xf1, 0x7b, 0xc9, 0xbc, 0xf7, 0x53, 0xa0, 0xaf, 0xbf,
	0xaf, 0x87, 0xb8, 0xc3, 0x82, 0x86, 0xba, 0x2a, 0xa9, 0x74, 0xe7, 0xd4, 0x9e, 0xb9, 0x6f, 0x1f,
	0xd1, 0xab, 0x75, 0x59, 0xae, 0x37, 0xe8, 0x0c, 0x8b, 0x7a, 0x35, 0x24, 0xb5, 0x45, 0x43, 0x62,
	0xab, 0x9d, 0x2f, 0xea, 0x1f, 0x1b, 0x70, 0xab, 0xe9, 0xa7, 0x13, 0x07, 0x7f, 0x18, 0xf8, 0xe3,
	0xe6, 0xa3, 0xfc, 0x16, 0x3a, 0x4a, 0x86, 0x2c, 0x66, 0x89, 0x97, 0x77, 0x94, 0xe4, 0x2f, 0xc0,
	0x27, 0x45, 0x1b, 0x0c, 0x3b, 0x31, 0x4b, 0x82, 0xdc, 0x0d, 0x3c, 0x86, 0xae, 0x44, 0xb3, 0xac,
	0x94, 0x26, 0x55, 0x16, 0xa1, 0x67, 0xb5, 0x7f, 0xaf, 0xf8, 0x08, 0x7a, 0xba, 0x5e, 0x6c, 0x94,
	0xf9, 0x86, 0x72, 0x6e, 0x48, 0x50, 0x6d, 0xc2, 0xab, 0x98, 0x25, 0xb7, 0xd9, 0xbd, 0xdb, 0x99,
	0x4e, 0xf7, 0xf2, 0xcc, 0xaa, 0xf9, 0x9d, 0xfe, 0xff, 0x82, 0x7f, 0x00, 0x58, 0x56, 0x28, 0x08,
	0xe5, 0x5c, 0x50, 0xe8, 0xc7, 0x2c, 0xe9, 0x66, 0x51, 0xea, 0x6a, 0xa4, 0xfb, 0x1a, 0xe9, 0x97,
	0x7d, 0xcf, 0x3c, 0x68, 0xdd, 0x23, 0x1a, 0xbc, 0x87, 0x67, 0x9f, 0x91, 0x6c, 0x23, 0x93, 0xa3,
	0xd1, 0x65, 0x61, 0x9a, 0xd0, 0x57, 0x52, 0x90, 0x08, 0x59, 0xec, 0x25, 0xdd, 0xec, 0xa6, 0x8d,
	0x61, 0x4d, 0xb9, 0x55, 0x06, 0xbf, 0x18, 0x44, 0x5f, 0xb5, 0x14, 0x84, 0x6d, 0xb8, 0x36, 0x1a,
	0xfe, 0xa8, 0xd1, 0x10, 0x7f, 0x09, 0x4f, 0x2c, 0xf9, 0xf9, 0x81, 0xd0, 0xb5, 0x9d, 0x27, 0xb2,
	0x91, 0xa8, 0x12, 0x85, 0x69, 0x24, 0x47, 0xea, 0xda, 0xce, 0x13, 0x79, 0x96, 0x84, 0xf7, 0x20,
	0x12, 0x6f, 0xde, 0xc2, 0xdd, 0x91, 0x87, 0x07, 0xe0, 0x7f, 0xaa, 0xc4, 0x8a, 0x7a, 0x8f, 0xf8,
	0x53, 0x08, 0x0e, 0x6a, 0x8f, 0x65, 0xbf, 0x19, 0xdc, 0xd8, 0x52, 0x33, 0xac, 0x76, 0x6a, 0x89,
	0xfc, 0x23, 0x04, 0x07, 0x18, 0xfc, 0xfe, 0x04, 0xe0, 0xb8, 0xf9, 0x0f, 0xa2, 0xb0, 0xcd, 0x72,
	0x8a, 0x6d, 0x0a, 0xcf, 0xcf, 0x30, 0xe1, 0xaf, 0xdb, 0x17, 0x2e, 0xf3, 0x8a, 0x2e, 0xec, 0x5a,
	0x3c, 0xb6, 0xf3, 0xbb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xce, 0xaa, 0x9e, 0x6e, 0xd8, 0x02,
	0x00, 0x00,
}
