// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/wallet/proto/wallet.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Wallet struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               int64                `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Wallet) Reset()         { *m = Wallet{} }
func (m *Wallet) String() string { return proto.CompactTextString(m) }
func (*Wallet) ProtoMessage()    {}
func (*Wallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_10749bf276df4454, []int{0}
}
func (m *Wallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wallet.Unmarshal(m, b)
}
func (m *Wallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wallet.Marshal(b, m, deterministic)
}
func (dst *Wallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallet.Merge(dst, src)
}
func (m *Wallet) XXX_Size() int {
	return xxx_messageInfo_Wallet.Size(m)
}
func (m *Wallet) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallet.DiscardUnknown(m)
}

var xxx_messageInfo_Wallet proto.InternalMessageInfo

func (m *Wallet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Wallet) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Wallet) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetWalletResponse struct {
	Data                 *Wallet  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletResponse) Reset()         { *m = GetWalletResponse{} }
func (m *GetWalletResponse) String() string { return proto.CompactTextString(m) }
func (*GetWalletResponse) ProtoMessage()    {}
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_10749bf276df4454, []int{1}
}
func (m *GetWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletResponse.Unmarshal(m, b)
}
func (m *GetWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletResponse.Marshal(b, m, deterministic)
}
func (dst *GetWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletResponse.Merge(dst, src)
}
func (m *GetWalletResponse) XXX_Size() int {
	return xxx_messageInfo_GetWalletResponse.Size(m)
}
func (m *GetWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletResponse proto.InternalMessageInfo

func (m *GetWalletResponse) GetData() *Wallet {
	if m != nil {
		return m.Data
	}
	return nil
}

type WithdrawRequest struct {
	TransId              string   `protobuf:"bytes,1,opt,name=trans_id,json=transId,proto3" json:"trans_id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_10749bf276df4454, []int{2}
}
func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (dst *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(dst, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetTransId() string {
	if m != nil {
		return m.TransId
	}
	return ""
}

func (m *WithdrawRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*Wallet)(nil), "proto.Wallet")
	proto.RegisterType((*GetWalletResponse)(nil), "proto.GetWalletResponse")
	proto.RegisterType((*WithdrawRequest)(nil), "proto.WithdrawRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletServiceClient interface {
	GetWallet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetWalletResponse, error)
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type walletServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletServiceClient(cc *grpc.ClientConn) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetWallet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, "/proto.WalletService/GetWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.WalletService/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
type WalletServiceServer interface {
	GetWallet(context.Context, *empty.Empty) (*GetWalletResponse, error)
	Withdraw(context.Context, *WithdrawRequest) (*empty.Empty, error)
}

func RegisterWalletServiceServer(s *grpc.Server, srv WalletServiceServer) {
	s.RegisterService(&_WalletService_serviceDesc, srv)
}

func _WalletService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WalletService/GetWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWallet(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WalletService/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWallet",
			Handler:    _WalletService_GetWallet_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _WalletService_Withdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/wallet/proto/wallet.proto",
}

func init() {
	proto.RegisterFile("pkg/wallet/proto/wallet.proto", fileDescriptor_wallet_10749bf276df4454)
}

var fileDescriptor_wallet_10749bf276df4454 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0x69, 0xf7, 0xff, 0xd7, 0xf5, 0x8e, 0x29, 0xe6, 0xa1, 0xd4, 0x8a, 0x38, 0xfb, 0xb4,
	0xa7, 0x16, 0x2a, 0x08, 0x0a, 0x3e, 0x08, 0x8a, 0xf8, 0x5a, 0x85, 0x3d, 0x8e, 0xcc, 0x5c, 0x6b,
	0x59, 0xdb, 0xc4, 0xf6, 0xd6, 0xe1, 0x57, 0xf0, 0x53, 0x8b, 0x49, 0x2a, 0xe8, 0xd8, 0x53, 0x38,
	0x39, 0x87, 0x73, 0x7e, 0x09, 0x9c, 0xa8, 0x75, 0x91, 0x6e, 0x78, 0x55, 0x21, 0xa5, 0xaa, 0x95,
	0x24, 0xad, 0x48, 0xb4, 0x60, 0xff, 0xf5, 0x11, 0x9d, 0x16, 0x52, 0x16, 0x15, 0x9a, 0xc4, 0xaa,
	0x7f, 0x49, 0xa9, 0xac, 0xb1, 0x23, 0x5e, 0x2b, 0x93, 0x8b, 0x8e, 0xff, 0x06, 0xb0, 0x56, 0xf4,
	0x61, 0xcc, 0x78, 0x0d, 0xde, 0x42, 0x97, 0xb2, 0x7d, 0x70, 0x4b, 0x11, 0x3a, 0x33, 0x67, 0x3e,
	0xca, 0xdd, 0x52, 0xb0, 0x00, 0x3c, 0x5e, 0xcb, 0xbe, 0xa1, 0xd0, 0xd5, 0x77, 0x56, 0xb1, 0x4b,
	0x80, 0x5e, 0x09, 0x4e, 0x28, 0x96, 0x9c, 0xc2, 0xd1, 0xcc, 0x99, 0x4f, 0xb2, 0x28, 0x31, 0x1b,
	0xc9, 0xb0, 0x91, 0x3c, 0x0d, 0x10, 0xb9, 0x6f, 0xd3, 0x37, 0x14, 0x5f, 0xc0, 0xe1, 0x3d, 0x92,
	0xd9, 0xcb, 0xb1, 0x53, 0xb2, 0xe9, 0x90, 0x9d, 0xc1, 0x3f, 0xc1, 0x89, 0xeb, 0xe5, 0x49, 0x36,
	0x35, 0x15, 0x89, 0x0d, 0x69, 0x2b, 0xbe, 0x85, 0x83, 0x45, 0x49, 0xaf, 0xa2, 0xe5, 0x9b, 0x1c,
	0xdf, 0x7a, 0xec, 0x88, 0x1d, 0xc1, 0x98, 0x5a, 0xde, 0x74, 0x4b, 0xcb, 0xec, 0xe7, 0x7b, 0x5a,
	0x3f, 0xec, 0x04, 0xcf, 0x3e, 0x1d, 0x98, 0x9a, 0xda, 0x47, 0x6c, 0xdf, 0xcb, 0x67, 0x64, 0xd7,
	0xe0, 0xff, 0xf0, 0xb0, 0x60, 0xeb, 0x0d, 0x77, 0xdf, 0xff, 0x14, 0x85, 0x96, 0x68, 0x9b, 0xfc,
	0x0a, 0xc6, 0x03, 0x16, 0x0b, 0x06, 0xee, 0xdf, 0x9c, 0xd1, 0x8e, 0xd6, 0x95, 0xa7, 0xf5, 0xf9,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0xb1, 0x5c, 0xb0, 0xe4, 0x01, 0x00, 0x00,
}
